name: Build DocMaster EXE

on:
  push:
    branches: [ main, master ] # عشان يشتغل سواء الفرع اسمه main أو master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconsole --onefile --icon="app_icon.ico" --name "DocMaster_Pro" --collect-all customtkinter main.py
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DocMaster-Windows-Release
        path: dist/DocMaster_Pro.exe
