name: Build DocSuite Ultimate

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter img2pdf pdf2image pandas openpyxl pdfplumber pillow pyinstaller

    - name: Build EXE (Optimized OneFile)
      run: |
        # استخدمنا --onefile تاني عشان نريحك من الفولدرات
        # وضفنا ميزة الـ No-Console عشان السرعة
        pyinstaller --noconsole --onefile --collect-all customtkinter --icon=app_icon.ico --name "DocSuite_Pro" main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DocSuite_Final_EXE
        path: dist/DocSuite_Pro.exe
